language: haskell
git:
  submodules: false
branches:
  only:
    - source
env:
  global:
    - secure: "eJUD6YrCYFv7DQoMQ3SsHIMsdrATCI3PEjNRUNMU4UvyU/QqCwiK+2SNRI0ybF1JCtzxtBm6Y5ZQ4dgHtvbbYOlRLxi4+wFFjZ4KbJTwfpl7WZPQXKdk2j+vV0nkEWHam+/VdF5BHbLNxvai4g649VGQbK/XPzS81DbrKgJvrGYQVyPyCk9w26G0jOqgU76ZO9uAwhP4I5u1VUQww/htWdMkBlB9MHShQTSrb8yM1AvgXq0yfWwd+FiseMGUS9rs4TjZmgUI6pySV138Op0NOQE8tLdQoaMJeB6WMjVsw/JsHsxz+wMevWojywWE3H25NT8CDm5QjSLtk9VSjnlhijeYnspthbSOGeD1vOycwHcGTiytaI8ZzcR8xaVw4uXXSAg37nSOGpN5wUuZrNp9N66sTttornQcnL+45R6CWug5SnG88XZYrufNA9SJXBikHYiQftSaJiZ9pYkrQgyPXDuASiKosUlOmyta0v+nYDxw2pkiOQx/KB6DXxbeSEyQDkzCR04kOCOIxBv8LuzCo/kGschWeUZtjKaFvU+cmRRSeXDHSJKwQaemTK7LSzitV6xEXDSdPyS7z8VuGNESyYXcma6iSkb4+9r9B2owtOgFTBYyj9WmL3181u97DcrKSVqBx7rYxuEhWuCjpDOHlfsPTurKCDD6/F8zsbWnnZ4="
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - curl http://deepscratch.github.io/hakyll-sandbox/hakyll-sandbox.tar.gz | tar xz
  - cabal sandbox init
  - cabal configure --disable-library-profiling --disable-tests --disable-library-coverage --disable-benchmarks --disable-split-objs
before_script:
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_NAME"
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..
script: cabal run rebuild
after_script:
  - cd _site
  - git status
  - git add --all
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push "https://$GH_TOKEN@$REPO_URL" master | grep -v http
  - cd ..
