language: haskell
ghc: 7.8
git:
  submodules: false
branches:
  only:
    - source
env:
  global:
    - secure: "WCcjLI3s3p4iHp4X/dj1SqUtmiax19x4qJqW6kQ7biCtt024Qjgrfps2x00xW953y42OH8NAMggLocyKn//yXwBhBgd44G51As7hW43ISTdMQakV4nu4JKsqi/9bkN8wv7InJpsC8FJaabOXIl2xjr9zM8azkdQA96z9tUGDvGANMNBBLKVEjmawZooTOmGaS2qUeMCh0o9J9iFbePKIS1WPrhxenqyG+CiPp77OfGDz5mUxGDSi2vK211XqNutJzjdY3YmLqU9VAoyUCHWe7j7d98atb7Ayk9koVVni4pgq3455SMxt/dXkW1HthPUP8sXGoHarIMGJBTp+gU5UZh13c9U6p/zk4B17gNRkOgaTpLPV6ylnYbj0fzU47D1nGAg8PJkyN5NSGhCHiKZfOR9R1qzfLGqZUzyzS0CdU8xsCsfL+cCCgh2Y58ceuSd9/Nh84XZHdk850iuB1ch05QrUCndqaQiEE1Mcqhe9rQsznBWdw0G5rkYG4ROTQ5QVxVSMngFy0IZr6SrMFd/bFtb6wgphqUADx+PC8dkojaJsrtqm3XwHd5OD5o0mehS/6vazg3cAdDsJULse6le/pDHwoNrCELh3scYczvWrBCQEBeAOY7F0e6Hf96x3TfHnUMO8Clt4yn6b5g3U1I2axePSWuCRfbIh/SckDTVGnd4="
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - curl http://deepscratch.github.io/hakyll-sandbox/hakyll-sandbox.tar.xz | tar Jx
  - cabal sandbox init
  - cabal configure --disable-library-profiling --disable-tests --disable-library-coverage --disable-benchmarks --disable-split-objs
before_script:
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_NAME"
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..
script: cabal exec -- ghc --make site.hs
after_script:
  - ghc-pkg check -v
  - cd _site
  - git status
  - git add --all
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push "https://$GH_TOKEN@$REPO_URL" master | grep -v http
  - cd ..
